steps:
  - name: ':docker: Build and push Docker image to tink-containers'
    timeout_in_minutes: 30
    branches: 'master'
    command: |
      # Build
      echo "$BUILDKITE_COMMIT"
      docker build -t catboost:$BUILDKITE_COMMIT .
      # Tag and push image with version number to repository
      docker tag catboost:$BUILDKITE_COMMIT gcr.io/tink-containers/catboost:$BUILDKITE_COMMIT
      gcloud docker -- push gcr.io/tink-containers/catboost:$BUILDKITE_COMMIT
